### ISSUE TITLE
II stage

### ISSUE THREAD

**Issue by rusdevops** [Loveskyrim/VkClient#1]
- `std::cerr` [здесь](https://github.com/Loveskyrim/VkClient/blob/master/sources/client.cpp#L39) и [здесь](https://github.com/Loveskyrim/VkClient/blob/master/sources/client.cpp#L78) больше подойдет.

**Comment by Loveskyrim** [comment]
closed this in https://github.com/Loveskyrim/VkClient/commit/65628e1b2b04e2a027d67765ce241774b9e59f71
